spring.application.name=front
spring.output.ansi.enabled=ALWAYS

# Server Configuration
server.port=8084

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,gateway

# Date formatting
spring.mvc.format.date=dd/MM/yyyy
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=Europe/Paris

# JWT Configuration
jwt.secret=SKZK3_uoqK8IM5HlWrOXQuDQNU5hIyWA6I7iGmMF65I
jwt.expiration=86400000