spring.application.name=note

# Server Configuration
server.port=8082

# dotenv
spring.config.import=optional:file:.env[.properties]
spring.output.ansi.enabled=ALWAYS

# MongoBD Connection
spring.data.mongodb.host=${DB_HOST}
spring.data.mongodb.port=${DB_PORT}
spring.data.mongodb.database=${DB_DATABASE}
spring.data.mongodb.username=${DB_USERNAME}
spring.data.mongodb.password=${DB_PASSWORD}

# Format des dates JSON
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Encodage
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Logs MongoDB (optionnel - pour debug)
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.medilabo.solution=DEBUG