spring.application.name=gateway
spring.output.ansi.enabled=ALWAYS

# Server Configuration
server.port=8080

# Logging
logging.level.org.springframework.cloud.gateway=info
logging.level.reactor.netty=info

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Gateway WebFlux 
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

spring.cloud.gateway.server.webflux.routes[0].id=patient
spring.cloud.gateway.server.webflux.routes[0].uri=lb://patient
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/patient/**

spring.cloud.gateway.server.webflux.routes[1].id=note
spring.cloud.gateway.server.webflux.routes[1].uri=lb://note
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/note/**

spring.cloud.gateway.server.webflux.routes[2].id=assessment
spring.cloud.gateway.server.webflux.routes[2].uri=lb://assessment
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/assessment/**

spring.cloud.gateway.server.webflux.routes[3].id=front-patient
spring.cloud.gateway.server.webflux.routes[3].uri=lb://front
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/patient/**

spring.cloud.gateway.server.webflux.routes[4].id=front-notes
spring.cloud.gateway.server.webflux.routes[4].uri=lb://front
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/notes/**

spring.cloud.gateway.server.webflux.routes[5].id=front-home
spring.cloud.gateway.server.webflux.routes[5].uri=lb://front
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/home

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,gateway