spring.application.name=assessment

# Server Configuration
server.port=8083

# dotenv
spring.config.import=optional:file:.env[.properties]
spring.output.ansi.enabled=ALWAYS

# Eureka Configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,gateway